channels:
  - letaylor
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas=1.1.3
  - numpy=1.19.2
  - scipy=1.5.2
  - scanpy=1.6.0
  - python-igraph=0.8.3
  - plotnine=0.7.1
  - kneed=0.7.0
  - louvain=0.6.1
  - leidenalg=0.8.2
  - pip
  - pip:
     - git+https://github.com/broadinstitute/CellBender.git
